# Generated by Django 4.1.6 on 2023-08-07 12:26

from django.db import migrations, models
from datetime import date

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=date(2023,8,7)),
        ),
    ]
